### ISSUE TITLE
謎への回答

### ISSUE THREAD

**Issue by HirokiTachiyama** [korosuke613/BWDM#7]
BwdmMain.kt, 24-27行目の

`    /**`
`     * 立山さんが残した謎`
`     */`
`    private const val buildDate = "2018-1-24 PM19:03(JST)"`

'-v' コマンドのバージョン情報にビルド日時を埋め込みたかったんだけど、Cの `__DATE__` みたいに、
Javaのコンパイル時に日時に置き換えるマクロ機能とかが見つからなかったんです。
なので、ダサさMAXだけど、mainクラスにハードコーディングしますた。

**Comment by korosuke613** [comment]
なるほど、そういうことだったんですか
コマンドに関わる部分はあんまりよく見てなかったです。
Javaはコンパイル日取ってこれないんですね(○ω○)
なんとかビルド日付取ってくるようにします。

**Comment by HirokiTachiyama** [comment]
任した！
